name: Check URLs

container:
  image: python:slim

test_task:
  pip_cache:
    folder: ~/.cache/pip
    fingerprint_script: echo $PYTHON_VERSION
    populate_script: pip install -r tests/requirements.txt
  test_script: python tests/check_links
